### PR TITLE
First Mandible Surgical Guide Created

### PR DESCRIPTION
**Pull request by mauigna06**
Andras can you check if the mandible surgical guides generation GUI has just enough buttons and parameters? I don't want something crowded or overcomplicated

### CODE REVIEW

**Comment by mauigna06** [comment]
Here is the workflow I developed to create the mandible surgical guides:
- click "Create saw boxes from first and last mandible planes"
- create a segment with both surgical guide bases
- create a mandibleBridgeModel using "Markups to Model" module and transform it a little bit with the interactive handles so it touches the biggerSawBoxes or the surgicalGuideBases slightly
- make boolean operations with models to create the mandible surgical guide

Result:
Screenshot8

@cmfsx Can you check out this branch and try to do a full surgical plan? Thank you

**Comment by mauigna06** [comment]
Now all "Update fibula planes over fibula line; update fibula bone pieces and transform them to mandible" is done with one button. And visualization is done with decimatedMeshes. 
In my computer with 4 mandible planes it takes 3 to 4 seconds to process. Here it takes approximately 6 seconds to update https://youtu.be/KYZlEP9mHvw?t=198, so I think we are okey. What do you think about this result?
I was thinking about adding other features as: 
- automatic fibulaLine creation using centerLine extraction from vmtk (or some algorithm that calculates the centroid of the intersection of one plane and the fibula model distally and proximally could be more exact)
- improve generateFibulaPlanesFibulaBonePiecesAndTransformThemToMandible time more
What else would you like?

**Comment by cmfsx** [comment]
@mauigna06 sorry for my inactivity in the last couple of weeks. 

I played around today with the Mandible-surgical-guide feature branch today. 

VSP component is now fantastic with real-time updates and there is nothing much to be improved in that.

Fibula guide component. 

In this branch, i came across the same problem with mitter boxes been placed too close to the fibula. 

Screenshot from 2021-03-18 11-06-52

In the mandible guide component,

without me doing any changes the last mitter box was created inside the mandible. Also, the default orientation of the mitter box was not good. How do we control the mitter box orientations? 

Screenshot from 2021-03-18 11-30-13

**Comment by mauigna06** [comment]
> In this branch, i came across the same problem with mitter boxes been placed too close to the fibula.

I suspect this problem is because fibulaSegment was not surfaceWrapSolidified because the algorithm has trouble positioning boxes when the fibula model mesh has holes inside. The mandible model should also be surfaceWrapSolidified. The first segment of each segmentation is used to create the bone models inside the module, so the surfaceWrapSolidifiedSegments should be the first segment in each segmentation.

> In the mandible guide component,
without me doing any changes the last mitter box was created inside the mandible. Also, the default orientation of the mitter box was not good. How do we control the mitter box orientations?

Now the boxes in the mandible are called sawBoxes (to differenciate them from miterBoxes). The position and the orientation are calculated by the algorithm but the part of titanium plate should be a little far from the first and last mandible planes because the algorithm may get confused.

Anyway, for this kind of problems always make an statement of what you wanted the module to do and what it did (like you did) and upload a complete example scene (without the scalar volumes). Please upload an example scene and I'll check it out

**Comment by mauigna06** [comment]
@lassoan when should I ask you to review this branch? It's almost finished I only have to solve the bugs Manjula found

**Comment by lassoan** [comment]
You can mark as "ready for review" anytime you are done with your changes.

**Comment by mauigna06** [comment]
With the centerFibulaLineButton and the makeAllMandiblePlanesRotateTogetherCheckBox in addition to all the previous GUI very exact Virtual Surgery Planning is posible. And I'm thinking on doing a frame for each fibulaSegment to make the cuts even more exact

**Comment by mauigna06** [comment]
Now there is an option to make the planning as accurate as it's possible (I don't think there is space for more improvement after this). One frame is created for each fibula bone piece.
It takes 3 times more time to execute so I recomend using it only when you finish the planning.

**Comment by mauigna06** [comment]
@cmfsx I found bugs on "Make all mandible planes rotate together" so don't use it to make the surgical planning. Thank you

**Comment by mauigna06** [comment]
@cmfsx You can use "Make all mandible planes rotate together" I think it works well. Remember that to have perfect planning you need to click on "Automatic mandibular planes positioning for maximum bones contact area" after you finished the surgical plan to get the most out of the module. May be this button will be automatically executed in next versions.

**Comment by cmfsx** [comment]
Hi @mauigna06 
please find the attached file. 
https://mah365-my.sharepoint.com/:u:/g/personal/manjula_herath_mau_se/EQyHu0tBsh9GqydWewN-5uABOWntiKYhRKiPYu08aLXymw?e=K2iLQr

1. Is there a special advantage in keeping the original Mandible hidden and decimated one visible rather than the other way around when bone models are created? because I thought the original will look better during the surgical planning and i believe you use the decimated one for calculations only. 
2. most of the bugs I found previously have been corrected
3. The only problem now is the make the saw boxes (Mandible cutting guide) to orient properly (according to the wishes of the surgeon. 
      a.One solution would be to make it rotate when you rotate the mandibular plane. (Disadvantage is that the fibula pieces also rotate with it when you do it. )  
      b. Make the saw boxes perpendicular to the mandibular curve by default and make it possible to adjust it further using the mandible plane if the surgeon wishes.

**Comment by mauigna06** [comment]
> Hi @mauigna06
please find the attached file.

Hi @cmfsx. Thank you for working on this. I checked the file and there where a two problems with the scene that made the sawBoxes not position well:
- The bone segmentations must be Wrap-Solidified in the segment editor (you have to install the SurfaceWrapSolidify extension first). Just click apply on Wrap Solidify after you created a bone segment (for example: using threshold and select island effects). After that correct any errors on the result (if there are any) and your segmentation is ready to use in the BoneReconstructionPlanner.
- First and last mandible cut planes should be at 5mm distance from the titanium thing that is in the mandible, because it's irregular shape confuses the positioning algorithm

> Is there a special advantage in keeping the original Mandible hidden and decimated one visible rather than the other way around when bone models are created? because I thought the original will look better during the surgical planning and i believe you use the decimated one for calculations only.

All the visualization is made with decimated model because they are faster to process on the dynamicModelerModule which makes the resectedMandible and the fibulaBonePieces

> most of the bugs I found previously have been corrected

If you find any more problems please check the above suggestions.

> The only problem now is the make the saw boxes (Mandible cutting guide) to orient properly (according to the wishes of the surgeon.
a.One solution would be to make it rotate when you rotate the mandibular plane. (Disadvantage is that the fibula pieces also rotate with it when you do it. )

I have thought about this. And I'm thinking that rotating the mandible planes one by one is not an useful option. A newly created plane can control rotation of all fibulaPlanes at the same time. Mandible planes X axis could be used as desired direction for the sawBoxes. FibulaPlanes X axis could be used to set up the direction of the miterBoxes allowing different directions (for example: superior and posterior). @cmfsx and @lassoan maybe we can talk more about this on next meeting.

@lassoan I'm letting this code for review because bug causes where identified.

**Comment by mauigna06** [comment]
Now the bug on the miterBox transform was corrected. And the new layout for the module is available.

newLayout

**Comment by mauigna06** [comment]
I have came to the conclusion that "more exact planning" algorithm takes too long without having enough benefits. If fibula line length and fibula pieces are colected from a fibula-segment that are less than 15cm (something typical I think): "More exact planning" algorithm only improves positioning by 0.3mm in fibula segments while taking 3 times more to execute.
The parameter that most impact good positioning are that fibulaLine is centered and that "Make all mandible planes rotate together" and "Automatic mandibular planes positioning for maximum bones contact area" are checked.
The only advantage that "more exact planning" algorithm has is that it makes bone pieces rotate around an axis that is very similar to the real bone axis while "common planning" make the bone rotate around an axis that is bit different to the real bone axis having the consecuence that when bone pieces are rotated they also translate a little bit. But this last thing, shouldn't be a problem considering the user will only change the angle of the mandibular planes at the start or the end of the planning.
What do you think @lassoan, @cmfsx?

**Comment by lassoan** [comment]
Computation time is should not be a major concern: if the preview is close enough to the full-quality results then waiting even a few minutes for the final export should be fine. The main reason for simplification should be less chances for errors and easier maintenance and testing of the code.

**Comment by mauigna06** [comment]
Planning with "more exact planning" checked moves the fibula bone pieces a little bit sometimes something as large as 1.5mm. So the plan that the surgeon made has to be modified to have into account these new positions and that means making small changes to the mandible planes position (waiting 3.5 times more each movement [in my computer 17 seconds for 3 bone pieces]) to restore the planed result. In my opinion this does not provide a good user experience. But I don't know, if you like it the way it is we leave it like that

**Comment by cmfsx** [comment]
> e. But I don't know, if you like it the way it is we leave it like that

I think we should leave it as it is for now. Because we have not yet properly evaluated it in a clinical setup. We need to actually first see It how both methods work in a live case. Afterwards if this  method is redundant we can remove it. For now I think we should leave it as it is.

**Comment by mauigna06** [comment]
> I think we should leave it as it is for now. Because we have not yet properly evaluated it in a clinical setup.

The way the transforms are made this is a WYSIWYG editor, the fibula surgical guide corresponds to the plan independently of it is "common planning" or "more exact planning".
There are not perfect correspondance between the faces of the fibula bone pieces in the mandible reconstruction but that is because of the irregular shape of the fibula. That error is about 0.6 or 0.8mm misalingment. And for what I saw in ProPlan CMF it also happens in their software.

> We need to actually first see It how both methods work in a live case.

@cmfsx do you plan to use the module for a clinical case? a cadaveric case? or at least do a full planning simulation (virtual planning, fibula surgical guide and mandible surgical guide) in the near future?

**Comment by mauigna06** [comment]
After trying the module for a while with non-centered fibula lines I saw that it doesn't make the planning impossible just unconfortable. It just changes the relation of the transformed fibula pieces with the origin of the mandible planes and changes the axis of rotation of transformed fibula bone pieces.

(These tests were made with "Make all mandible planes rotate together" and "Automatic mandibular planes positioning for maximum bones contact area" checked)

I have no conclusion of if using a custom frame for each fibula bone piece does improve the planning quality (making the overlap of touching faces of the meshes greater)

**Comment by cmfsx** [comment]
> @cmfsx do you plan to use the module for a clinical case? a cadaveric case? or at least do a full planning simulation (virtual planning, fibula surgical guide, and mandible surgical guide) in the near future?

Yes, since we want to publish on this I have filed for IRB approval. hopefully, I will get it soon, otherwise, we will need ERC which is a bit more complicated. We need it to publish in a good journal.  We can do complete planning only without any of it.

**Comment by mauigna06** [comment]
Please @cmfsx do mandible surgical guides for different cases to check that automatic sawBoxes positioning works well (sawBoxes not touching the teeths and with good position and orientation)

**Comment by mauigna06** [comment]
@lassoan it would be great if you review this branch. Sorry if you are very busy, I don't know if you got the "review request notification"

**Comment by mauigna06** [comment]
@cmfsx could you test virtual surgical planning thoroughly? I made a change so that fibulaPlanes position and orientations on rotations of mandiblePlanes in "more exact planning" take the same to compute that in "common planning". This makes the code a little more complex and increases the chances of bugs. I tested it and it works well for me but please try to find if there are any bugs (eg: add mandiblePlanes, delete them, move them, rotate them, check that everything works as expected)

I'll try to create a button to auto-order mandiblePlanes if you create one mandiblePlane in between others soon.

**Comment by cmfsx** [comment]
Hi @mauigna06 ,

I use this branch with the latest commit, and I came across several problems. 

First, in the last commits, it seems the rotation of the mandible cutting planes is broken. 

Screenshot_12

This happens if I try to rotate the mandible cutting planes.  this error resets if I again use a translation movement. But if I do rotation again the error comes. So  I could not really test the VSP in detail because of this error. 

Most importantly, 

I stick to the original data set we used, and the saw box placement in the mandible is not good.  I understand that you said the positioning algorithm finds it hard when the cuts are close to the reconstruction plate in the mandible. But the solution is not moving the planes away from it. I tried that way too, and it gives better results, but it is not possible in real life. We need to come up with a better solution to position the mandible saw boxes.  

I suggest is it possible to constraint the saw boxes to the plane and allow the user to orient it by rotating and translating constrained to the plane so the directions of the cut are not changed but only the position of the saw box is a change to the place the surgeon wants. 

Can we discuss the mandible saw box position over a video call when you have time as it is hard to explain. 

Few other comments are, 

1. If you try to create a fibula line before creating bone models from segmentation, the line cannot be created. (Curve can be created as usual). Only after creating the bone models are you able to create the fibula line. (is this by design or just a bug? I suppose if it is by design curve should not be created as well. )

2. When you hit create bone models from segmentation, hide the segments that you use to create the models by default. 

3. The mandible saw boxes appear in view two, so need to hide it from view 2 (fibula view)

**Comment by mauigna06** [comment]
> First, in the last commits, it seems the rotation of the mandible cutting planes is broken.

With the last commit it should be fixed. Please try to test the virtual surgical planning to see if you can find more bugs.

> I stick to the original data set we used, and the saw box placement in the mandible is not good. I understand that you said the positioning algorithm finds it hard when the cuts are close to the reconstruction plate in the mandible. But the solution is not moving the planes away from it. I tried that way too, and it gives better results, but it is not possible in real life. We need to come up with a better solution to position the mandible saw boxes.
I suggest is it possible to constraint the saw boxes to the plane and allow the user to orient it by rotating and translating constrained to the plane so the directions of the cut are not changed but only the position of the saw box is a change to the place the surgeon wants.

I also had this idea of giving interaction handles to the sawBoxes to move them. It can be done. And motion can be constrained so that it does't alter the planned resection. I'll programme that in the near future.

> Can we discuss the mandible saw box position over a video call when you have time as it is hard to explain.

I think we can do a video call soon. I'll try to schedule it.

> If you try to create a fibula line before creating bone models from segmentation, the line cannot be created. (Curve can be created as usual). Only after creating the bone models are you able to create the fibula line. (is this by design or just a bug? I suppose if it is by design curve should not be created as well. )

It's kinda a bug but I think it would be desirable to be able to position the fibulaPlanes according to the mandiblePlanes and the fibula line without needing to input the bone models or segmentations. So how the module works can be checked without segmentations or bone models. What do you think? Or coding this would spend time in something not so important?

> When you hit create bone models from segmentation, hide the segments that you use to create the models by default.

Done

> The mandible saw boxes appear in view two, so need to hide it from view 2 (fibula view)

Done

**Comment by cmfsx** [comment]
> coding this would spend time in something not so important?

yes, I think this part is not very important for now.  

I think we should give our effort at figuring out how to place the mandibular saw boxes properly.

**Comment by mauigna06** [comment]
@cmfsx now sawBoxes are moveable, please check the latest commit and give feedback. In a future version of the code only X and Y axis will be shown for translation and only Z axis will be shown for rotation so the surgical plan is conserved

**Comment by cmfsx** [comment]
@mauigna06 

I tried the latest version. The Saw box interactions are excellent. With common sense, even it not been constrained to the plane is not a big issue. 

I came across few problems though. in the Mandible guide by default sawBoxesModels are hidden and then when I create the guide base the sawBoxesModels are not subtracted and therefore there is no slot created.  
Also, the holes were not created in the guide base for some reason.  

Screenshot_42

**Comment by mauigna06** [comment]
> I came across few problems though. in the Mandible guide by default sawBoxesModels are hidden and then when I create the guide base the sawBoxesModels are not subtracted and therefore there is no slot created.

I suspect slots are being created. I suggest you hide "biggerSawBoxes Models" to see the slots. If not upload a scene and I'll check.

> Also, the holes were not created in the guide base for some reason.

Please check that "Mandible Cylinders Models" is not empty. Also check that the fiducialList selected is correct (verify is not a fibulaCylinderFiducialList). After that click "Create cylinders from fiducial list and mandible surgical guide base" and try making the surgical guide again and tell me how it goes.

**Comment by cmfsx** [comment]
> I suspect slots are being created. I suggest you hide "biggerSawBoxes Models" to see the slots. If not upload a scene and I'll check

The problem persists, Both the screw holes and the slot is not created. 

https://drive.google.com/file/d/1VXJ6P0wNO_PMdBdgOFTaWHVLBE8D45Zd/view?usp=sharing

**Comment by mauigna06** [comment]
> The problem persists, Both the screw holes and the slot is not created.

The bug was solved. Please tell me if you have any more problems

**Comment by cmfsx** [comment]
> Please tell me if you have any more problems

I find it if we create the cutting planes in the wrong order and then simulate it then again or-order the planes proeplry the simulation is not corrected. If we create planes in wrong order but re-order them properly before doing the simulation ( pressing the update button) then simulation work. 



Screenshot_35

**Comment by mauigna06** [comment]
> I find it if we create the cutting planes in the wrong order and then simulate it then again or-order the planes proeplry the simulation is not corrected. If we create planes in wrong order but re-order them properly before doing the simulation ( pressing the update button) then simulation work.

You have to reorder them using the data module. If not it doesn't work I don't know why.

It is not much work to implement a button to reorder mandible planes or to reorder the planes when a new plane is added. I can do that if you want

**Comment by cmfsx** [comment]
> You have to reorder them using the data module. If not it doesn't work I don't know why.

Ok I will try it.

**Comment by mauigna06** [comment]
Now mandiblePlanes are ordered when a new mandiblePlane is added.

@cmfsx Please do a last test to the module (VSP and surgical guides), if everything is okay I'll merge this branch to main

**Comment by mauigna06** [comment]
This branch is quite tested right now. I'll merge

**Pull request merged**
